spring.application.name=Tasks
spring.datasource.url=jdbc:postgresql://localhost:5432/Tasks>
spring.datasource.username=USUARIO_BD
spring.datasource.password=SENHA_BD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=<create | create-drop | update | validate | none>
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect