spring.application.name=Tasks

spring.datasource.url=jdbc:postgresql://localhost:5432/tasks
spring.datasource.username=${USUARIO_DB}
spring.datasource.password=${SENHA_BD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect